dist: xenial
sudo: required
language: c

before_script:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt

script:
  - curl -s 'https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh' | bash

env:
  global:
    secure: bZyuJkHSrDkuoSeYCJiMM/egf7RtWLRxXGSQ5+1gIZiNhc8vWjfB1Xd4ap4QEOiI2xvkuiY2iiPhuV17K4cPa7otBbWisZHVqfmyAQTnzrpxmKtAt5EbyrkSReLfD5+MARmLh43RKV7CNFrbkRXxOuR8KkyYGXlP1LkUpyf1n0U=
    - COVERITY_SCAN_BRANCH_PATTERN="coverity_scan"
    - COVERITY_SCAN_NOTIFICATION_EMAIL="coverityscan@pureftpd.org"
    - COVERITY_SCAN_COMMAND_PREPEND="./autogen.sh ; ./configure"
    - COVERITY_SCAN_BUILD_COMMAND="make -j4"
    - COVERITY_SCAN_PROJECT_NAME="$TRAVIS_REPO_SLUG"
    - COVERITY_SCAN_PROJECT_VERSION="dev"
    - COVERITY_SCAN_PROJECT_DESCRIPTION="libsodium"

apt:
  packages:
    - ca-certificates
